name: flashcardsnew
description: A sample Polymer application
dependencies:
  polymer: any
  paper_elements: any
  test: any
transformers:
- polymer:
    entry_points: web/flashcardsnew.html
    inline_stylesheets:
      web/resources/bootstrap-3.1.1-dist/css/bootstrap.css: false
      web/resources/flashcardsnew.css: false
      web/resources/paperbuttons.css: false
    csp: true